### ISSUE TITLE
Error While Training with Yelp Dataset 

### ISSUE THREAD

**Issue by kelvict** [ematvey/deep-text-classifier#3]
While I trained model with Yelp Dataset prepared by yelp_prepare.py,  I got error log as follow.
The code has been ran with tensorflow 1.0.1 and Python 2.7.12 in Linux.
```
....
step 251, loss=1.55983, accuracy=0.2, t=19.89, inputs=(30, 30, 30)
Traceback (most recent call last):
  File "worker.py", line 220, in <module>
    main()
  File "worker.py", line 215, in main
    train()
  File "worker.py", line 195, in train
    ], fd)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[28,0,6] = 50000 is not in [0, 50000)
	 [[Node: tcm/tcm/embedding/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@tcm/embedding/embedding_matrix"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](tcm/embedding/embedding_matrix/read, _recv_tcm/inputs_0)]]

Caused by op u'tcm/tcm/embedding/embedding_lookup', defined at:
  File "worker.py", line 220, in <module>
    main()
  File "worker.py", line 215, in main
    train()
  File "worker.py", line 165, in train
    model, saver = model_fn(s)
  File "worker.py", line 97, in HAN_model_1
    is_training=is_training,
  File "/data/zhiheng/project/deep-text-classifier/HAN_model.py", line 63, in __init__
    self._init_embedding(scope)
  File "/data/zhiheng/project/deep-text-classifier/HAN_model.py", line 102, in _init_embedding
    self.embedding_matrix, self.inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/embedding_ops.py", line 111, in embedding_lookup
    validate_indices=validate_indices)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1359, in gather
    validate_indices=validate_indices, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): indices[28,0,6] = 50000 is not in [0, 50000)
	 [[Node: tcm/tcm/embedding/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@tcm/embedding/embedding_matrix"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](tcm/embedding/embedding_matrix/read, _recv_tcm/inputs_0)]]
```

**Comment by ematvey** [comment]
Edge case. Interesting how I didn't encounter it before. Fixed it with #377040e6a8a788d15c913a2a0ff335b9bc8f1cc5 so that preprocessed data remains compatible, but not checkpoints.
